[package]
name = "find_empty_workspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i3_ipc = "0.14.0"
structopt = "0.3.26"
